name: Metrics
on:
  # Update each hour
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: noverse
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: nvgh-metrics.svg
          token: ${{ secrets.RM_TOKEN }}
          user: 5Noxi
          template: classic
          base: header, repositories
          config_order: base.header, introduction, languages, base.activity, base.repositories, isocalendar, activity, screenshot
          config_timezone: Europe/Berlin
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_mode: image
          plugin_screenshot_selector: body
          plugin_screenshot_title: Website
          plugin_screenshot_url: https://5noxi.github.io/projects.html
          plugin_screenshot_viewport: {
  "width": 1280,
  "height": 1280
}

          plugin_screenshot_wait: 1000