name: Metrics
on:
  # 3H
  schedule: [{cron: "0 */3 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}

          config_timezone: Europe/Berlin
          base: header, activity, repositories
          plugin_isocalendar: yes
          plugin_languages: yes

          config_order: base.header, base.activity, base.repositories, isocalendar, languages
